### ISSUE TITLE
Exception after starting MqttAgent Sequence contains more than one matching element 

### ISSUE THREAD

**Issue by marspox** [OPCFoundation/UA-IIoT-StarterKit#16]
Hi,
I have included a latest preview version of OPC.Ua.PubSub into MqttAgent.
Whole application has been build success.
But after running app I'm getting error sequence contains more than one matching element.
I'm not able to identify a place in code when this exception is throwen.
![MqttAgent](https://user-images.githubusercontent.com/7716006/147101660-38879f80-7c00-422f-b5f7-e44430378c2a.PNG)

Any idea what can be wrong?

**Comment by opcfoundation-org** [comment]
Which codebase are you using? Line 47 is not a valid line number for the current codebase.

Check the list of commands that are being added in your version for duplicates.

**Comment by marspox** [comment]
Thanks for giving starting point.
The exception is related with duplicated '-p' option, once for password (-p|--password) second for publisher(-p|--publisher).

**Comment by opcfoundation-org** [comment]
You can delete the password option. This needs to be fixed.
