### ISSUE TITLE
Project setting "Treat warnings as errors" fails compilation

### ISSUE THREAD

**Issue by ag-ctlg** [OPCFoundation/UA-IIoT-StarterKit#17]
Projects are failing compilation in Visual Studio 2022 (my installed version is 17.6.4) because of the setting "Treat warnings as errors".
I don't know whether earlier versions of VS didn't have the warnings that are now appearing in VS 2022.

Either the warnings should be fixed or the setting disabled. Since there are only two warnings reported I would strongly suggest fixing them and keeping the zero-warning policy.

![grafik](https://github.com/OPCFoundation/UA-IIoT-StarterKit/assets/99892060/ee27deb7-3967-4e0b-af41-4eeb81376515)

Affected projects are:
- Opc.Ua.Configuration
- Opc.Ua.PubSub
- Opc.Ua.Server

Warnings reported are:
- CA1854: Prefer a 'TryGetValue' call over a Dictionary indexer access guarded by a 'ContainsKey' check to avoid double lookup
- CA1852: Type 'CertValidationSuppressibleStatusCodes' can be sealed because it has no subtypes in its containing assembly and is not externally visible

**Comment by randy-armstrong** [comment]
Will look at.

**Comment by ag-ctlg** [comment]
@randy-armstrong sorry, I was about to close this issue and reopen it in the correct repository. The projects mentioned are from the [UA-.NETStandard](https://github.com/OPCFoundation/UA-.NETStandard) repo.

**Comment by randy-armstrong** [comment]
This repo links to .NETStandard. If it is general issue with .NETStandard you need to raise the issue there.

**Comment by ag-ctlg** [comment]
This repository links to an older version of the UA-.NETStandard repository (from 2021). The current version of that repository compiles without errors and the list of ignored warnings in their projects is quite long:
![grafik](https://github.com/OPCFoundation/UA-IIoT-StarterKit/assets/99892060/c54cb9dc-74fb-4ccc-8236-f4a3973c21e7)

Perhaps you should update this project's dependency to reference a newer version or HEAD?
