### ISSUE TITLE
Thread pool exhaustion issues for many writer groups

### ISSUE THREAD

**Issue by jnsjll** [OPCFoundation/UA-IIoT-StarterKit#20]
Hello there,

I am running into thread pool starvation issues when publishing to a couple (~50) of MQTT topics.

The problem seems to be that the `IntervalRunner` used for each `WriterGroupDataType` / `UaPublisher` calls the `PublishMessages` method on a thread pool thread which will block on a lock in `MqttPubSubConnection.PublishNetworkMessage`:

![pubsubthreadpoolexhaustion](https://github.com/OPCFoundation/UA-IIoT-StarterKit/assets/123474392/b9334de6-8c82-47db-abbb-f838f6a07d4d)

Here is a fork that reproduces the issue: https://github.com/jnsjll/UA-IIoT-StarterKit

Do you have any suggestions?

**Comment by opcfoundation-org** [comment]
The architecture has been changed a lot with 1.05.03. 
Need to confirm that it still exists.

**Comment by opcfoundation-org** [comment]
Can be reopened if the issue still exists.
