### ISSUE TITLE
Setup Linux Readme seems to be outdated

### ISSUE THREAD

**Issue by fpethig** [OPCFoundation/UA-IIoT-StarterKit#22]
The project UaMqttConsole/UaMqttConsole.csproj mentioned in https://github.com/OPCFoundation/UA-IIoT-StarterKit/blob/master/docs/setup/linux/README.md does not exist (anymore?).

**Comment by samuelbprescott** [comment]
I also just ran into this. MQTT Spy is very outdated, as well. The whole tutorial could do with a refresh.

**Comment by opcfoundation-org** [comment]
What free alternatives are there for MQTT spy?
