### ISSUE TITLE
Publisher: DataSetMessage.SequenceNumber not sequential

### ISSUE THREAD

**Issue by ZbynekZ** [OPCFoundation/UA-IIoT-StarterKit#3]
DataSetMessage.SequenceNumber should be incremented by exactly one. In my observation, it is far more common for it to be incremented by 2 or even larger amount.

**Comment by opcfoundation-org** [comment]
It is not clear what needs to be fixed.

**Comment by ZbynekZ** [comment]
Observed behavior (the two messages are on the same topic, opcua/PC-ZBYNEKZ-4/full/Gate1):

One message published is:

{"MessageId":"b5000411-3847-49d9-83f5-16e36cda3a43","MessageType":"ua-data","PublisherId":"PC-ZBYNEKZ-4","DataSetClassId":"95254774-8145-4df7-92b5-789e5dca9a0d","Messages":{"DataSetWriterId":3,"SequenceNumber":125,"MetaDataVersion":{"MajorVersion":1,"MinorVersion":0},"Timestamp":"2021-06-10T14:30:15.0986718Z","Payload":{"State":{"Type":1,"Body":false},"CycleCount":{"Type":7,"Body":52}}}}

A message that immediately follows is:

{"MessageId":"ddae5c06-aa90-48e4-94e8-109440dbf2ba","MessageType":"ua-data","PublisherId":"PC-ZBYNEKZ-4","DataSetClassId":"95254774-8145-4df7-92b5-789e5dca9a0d","Messages":{"DataSetWriterId":3,"SequenceNumber":130,"MetaDataVersion":{"MajorVersion":1,"MinorVersion":0},"Timestamp":"2021-06-10T14:32:37.319316Z","Payload":{"State":{"Type":1,"Body":false},"CycleCount":{"Type":7,"Body":54}}}}

Expected behavior:

The SequenceNumber in the second message should be 126, not 130.

**Comment by opcfoundation-org** [comment]
Pushed fix. It requires a sub module update (bug in UAPubSub library).

**Comment by ZbynekZ** [comment]
This works OK now.
