### ISSUE TITLE
Publisher: MetaDataVersion is invalid

### ISSUE THREAD

**Issue by ZbynekZ** [OPCFoundation/UA-IIoT-StarterKit#4]
Observed behavior: Published messages contain "MetaDataVersion":{"MajorVersion":1,"MinorVersion":0}

This does not look like a valid metadata version. The fields actually represent timestamps (of type VersionTime). And, MinorVersion can never be smaller than MajorVersion.

Expected behavior: MetaDataVersion should be a valid and realistic ConfigurationVersionDataType.

**Comment by opcfoundation-org** [comment]
Pushed a fix.

**Comment by ZbynekZ** [comment]
This is OK now.
