### ISSUE TITLE
 UADP NetworkMessage support

### ISSUE THREAD

**Issue by mpostol** [OPCFoundation/UA-IIoT-StarterKit#5]
Great work. Very useful, but still some topics are not clear.  @randy-armstrong  as you asked I try to do my homework. Let me stress, the main purpose of the following questions is to learn how to improve (update) the description I have provided many years ago and maybe it is obsolete now. 

- [UA Part 14: PubSub Main Technology Features](https://commsvr.gitbook.io/ooi/reactive-communication/readme.pubsubmtf).

1. What is the reason to use `JSON` encoding? Is it possible to use binary encoding instead?
1. What is the relationship between the metadata and the Information Model? (see also [What is Information Model vs Semantic-data](https://github.com/mpostol/OPC-UA-OOI/discussions/587)
1. Is there any relationship between the metadata, Information Model, and MQTT topic? 
1. `PubSub` can use four protocols and two encodings. It yields an impressive number of incompatible combinations. How to select an appropriate one? Are there any best practice rules helping to select the appropriate combination?
1. Based on this example what I need to do to select a different combination of the underlying protocol/encoding?
1. Somones call `MQTT` a transport protocol. I know it is not a transport layer, but what is the difference between a transport and no transport protocol? Is IP a transport protocol for UDP for example? Is proposed by me the `Transport protocol stack architecture` correct?

**Comment by opcfoundation-org** [comment]
1) The StarterKit is a teaching tool. JSON makes it easier to see what goes on the wire. Later versions will support binary.

2) The metadata includes a subset of the information model (specifically properties and their values). The WG is looking a including subsets of the address space using a JSON nodeset format.

3) The metadata contains properties from the information model. The MQTT topic name is the BrowseName of the Object being monitored (not required - just what the sample is doing).

4)  Users look for products that support the TransportProfile(s) they want to use. There are exactly 2 for MQTT:
[PubSub MQTT UADP](http://opcfoundation.org/UA-Profile/Transport/pubsub-mqtt-uadp)
[PubSub MQTT JSON](http://opcfoundation.org/UA-Profile/Transport/pubsub-mqtt-json)

OPC UA profiles exist to reduce the number of permutations and combinations to a manageable set.

5) The current example only supports the 'PubSub MQTT JSON' profile. Future updates will add more.

6) The OSI model is not the right frame of reference. MQTT is a transport from the perspective of OPC UA and that is why the term is used. From a UA perspective any protocol that allows applications to send OPC UA messages is a "transport protocol".

**Comment by mpostol** [comment]
@opcfoundation-org thanks for the explanation. Not sure if everything is clear for me, but concluding there is no need for any modification of my stuff.

BTW: `There are exactly 2 for MQTT:` - yes, exactly - we have metric and inch bolt standards (only two), so let try to combine both in one standard and say that we have only two bolt profiles. The same is with "transport protocol" - I hope you mean "transport stack". My point is that it is not just a wording problem.

**Comment by opcfoundation-org** [comment]
Different applications have different requirements and there is no "one size fits all".

UA Binary is faster and provides end to end security but requires a UA binary parser on both ends. This is not a reasonable expectation if you are sending data to the cloud.

UA JSON is easier for non UA applications to consume but is less efficient.

OPC UA manages the complexity of multiple profiles with a layered model and a common configuration model. This makes it it easier build and maintain support for multiple transports.

**Comment by mpostol** [comment]
@opcfoundation-org  I know why people use different protocols for ages addressing many needs, namely performance, security, robustness, round trip time, jitter, and even power consumption. For this approach, we complain that it doesn't work in a multi-vendor environment.

Now we claim that there is a standard the relaxes this problem by using a common name. Instead of different protocols, we have different profiles still not interoperable profiles. Again, it doesn't work in the multi-vendor environment. My point is that we cannot call it standardization. We cannot even call it normalization. Maybe harmonization is a good term.

I am aware that it is impossible to have just one profile. The question is how to deal with that. Just ad hoc, I have the following proposals:

- limit the number of profiles
- select only one that must be implemented in all products
- postpone the selection of the working profile up to the run-time

BTW, from my recent research, I can derive a conclusion that JSON serialization is useless for PubSub (and in general for OPC UA) because direct interoperability based on the edge concept is not applicable to all scenarios. I proposed a solution that can be applied to any cloud (not only Azure) without any additional assumptions. To get more check out my presentation on YouTube

[Object-Oriented Internet Cloud Interoperability; Presentation - executive summary on YouTube](https://youtu.be/yXH09wuWEcA)

To get more check out the full story 

[Object-Oriented Internet Cloud Interoperability](https://www.researchgate.net/publication/352289895_Object-Oriented_Internet_Cloud_Interoperability)

Removing useless JSON from the specification will limit the number of profiles significantly and it also removes some critical errors like custom JSON schema definition.

In general, try to follow the current science, but not try to be in front of the science. The specification is only a snapshot of what we have but not a guide to custom products.

**Comment by mpostol** [comment]
@opcfoundation-org BTW From `MQTT is a transport from the perspective of OPC UA` i can derive the statement that `OPC UA  is just one of infinitive number of user applications from the perspective of MQTT`.

In this context, my next doubt is what is a reason to put a pubsub protocol (OPC UA PubSub) atop of next pubsub protocol (MQTT).

**Comment by opcfoundation-org** [comment]
JSON is useful when the consumers of the data know have no ability to parse UA binary messages.
This is the case when data is being pushed to cloud based analytics engines or to browser based UIs.

UA binary is most useful when both sides are full UA applications.
This is the case for controller to controller communication between factory applications (which can be communicating via the Internet).
