### ISSUE TITLE
git clone information missig

### ISSUE THREAD

**Issue by koepalex** [OPCFoundation/UA-IIoT-StarterKit#6]
The information that it is required to add `--recurse-submodules` to the _git clone_ is missing in readme.

**Comment by opcfoundation-org** [comment]
The sequence of commands:

```
git clone https://github.com/OPCF-Members/UA-IIoT-StarterKit.git
cd UA-IIoT-StarterKit
git submodule update --init
```

should do the same thing.

**Comment by opcfoundation-org** [comment]
Closing a stale issue.
